version: "3.9"

services:
  www:
    build:
      context: ../../
      dockerfile: .devcontainer/v2/Dockerfile
    image: kbin
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2019/metrics || exit 1"]
    ports:
      - 8080:8080
    volumes:
      - ../../docker/v2/storage/caddy_config:/config
      - ../../docker/v2/storage/caddy_data:/data
      - ../../docker/v2/storage/media:/var/www/html/public/media
    environment:
      - SERVER_NAME=:8080  # the addresss that the web server binds
      - PHP_FASTCGI_HOST=php:9000  # caddy forward traffic to this host via fastcgi
      - MERCURE_JWT_SECRET=!ChangeThisMercureHubJWTSecretKey!
      - MERCURE_PUBLISHER_JWT_KEY=$MERCURE_JWT_SECRET
      - MERCURE_SUBSCRIBER_JWT_KEY=$MERCURE_JWT_SECRET
    depends_on:
      - php

  php:
    build:
      context: ../../
      dockerfile: .devcontainer/v2/Dockerfile
    image: kbin
    command: php-fpm
    healthcheck:
      test: ["CMD-SHELL", "REQUEST_METHOD=GET SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping cgi-fcgi -bind -connect localhost:9000 || exit 1"]
    volumes:
      - ../../docker/v2/storage/media:/var/www/html/public/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger:
    build:
      context: ../../
      dockerfile: .devcontainer/v2/Dockerfile
    image: kbin
    command: bin/console messenger:consume async --time-limit=3600
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'messenger[:]consume' || exit 1"]
    volumes:
      - ../../docker/v2/storage/media:/var/www/html/public/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger_ap:
    build:
      context: ../../
      dockerfile: .devcontainer/v2/Dockerfile
    image: kbin
    command: bin/console messenger:consume async_ap --time-limit=3600
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'messenger[:]consume' || exit 1"]
    volumes:
      - ../../docker/v2/storage/media:/var/www/html/public/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis:alpine
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    volumes:
      - ../../docker/v2/storage/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    environment:
      - REDIS_PASSWORD=!ChangeThisRedisPass!

  db:
    image: postgres:13-alpine
    volumes:
      - ../../docker/v2/storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kbin
      - POSTGRES_USER=kbin
      - POSTGRES_PASSWORD=!ChangeThisPostgresPass!

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=kbin
      - RABBITMQ_PASSWORD=!ChangeThisRabbitPass!
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ../../docker/v2/storage/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672

  # Add your favorite reverse proxy (e.g nginx) which accept incoming HTTPS
  # traffic and forward to http://www:8080
  # nginx:
  #  image: nginx
  #  ports:
  #    - 443:443
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
